## INFO ##
# plugin made with <3 by Delected
# use https://www.spigotmc.org/attachments/example2-png.188806/ as a reference for color codes
# replace special characters with unicode (I.E: \u00BB will become »)
# way cooldowns get evaluated in order: [TBD: Global] -> Item -> Blacklisted Area

########################
#        General       #
########################

# message sent when player is on cooldown. Use {time} to display the time
cooldown_message: "&6&lAbilities &8\u00BB &7Woah, slow down there! You're on cooldown for another &6{time} &7seconds!"

######################################################## TBD, not implemented yet
# cooldown for every ability (seconds)
global_cooldown_time: 10

# cooldown message for every ability. Use {time} to display the time
global_cooldown_message: "&6&lAbilities &8\u00BB &7You cannot use another ability for &6{time} &7seconds!"
#########################################################

# coords of an area where abilities can't be used (usually spawn)
ability_blacklisted_area:
  x1: 0
  z1: 0
  x2: 0
  z2: 0

# message sent when player
ability_blacklisted_message: "&6&lAbilities &8\u00BB &7You cannot use abilities in this area!"

########################
#      Rotten Egg      #
########################

# you can use {hit} to display hit player's name, and {thrower} to display thrower's name
rotten_egg:

  item:
    material: STONE:1


  message_to_egg_hit: "&6&lAbilities &8\u00BB &6{thrower} &7hit you with a rotten egg, giving you poison, nausea, and blindness!"

  message_to_egg_thrower: "&6&lAbilities &8\u00BB &7You hit &6{hit} &7with a rotten egg, giving them poison, nausea, and blindness!"

  ##### levels/amplifiers for each effect (number must be 1-255) ####
  nausea_level: 1
  poison_level: 1
  blindness_level: 2

  #### duration/time for each effect (time in seconds) ####
  nausea_duration: 10
  poison_duration: 5
  blindness_duration: 10

  # Egg item display name
  egg_displayname: "&6Rotten Egg"

  # Egg item lore
  egg_lore:
    - "&8Gives a player the following"
    - "&8effects when hit:"
    - "&7- Nausea 1 &e(10s)"
    - "&7- Poison 1 &e(5s)"
    - "&7- Blindness 1 &e(10s)"

  # cooldown time in seconds
  egg_cooldown_time: 30



########################
#   Switcher Snowball  #
########################

snowball_displayname: "&5Switcher Snowball"

snowball_lore:
  - "&8Switches you"
  - "&8with the hit player!"

message_to_snowball_hit: "&6&lAbilities &8\u00BB &6{thrower} &7hit you with a switcher snowball!"

message_to_snowball_thrower: "&6&lAbilities &8\u00BB &7You hit &6{hit} &7with a switcher snowball!"

# cooldown time in seconds
snowball_cooldown_time: 30

########################
#      Stun Coal       #
########################

# duration of stun (in seconds)
stun_duration: 5

stun_displayname: "&0Stun"

stun_lore:
  - "&8Stuns a player for 5 seconds,"
  - "&8preventing pearling,"
  - "&8building, and moving."

# cooldown time in seconds
stun_cooldown_time: 45

# you can use {hit} to display hit player's name, and {hitter} to display hitter's name
message_to_stun_hit: "&6&lAbilities &8\u00BB &6{hitter} &7hit you with a stunner, preventing you from pearling, building, and moving!"

message_to_stun_hitter: "&6&lAbilities &8\u00BB &7You hit &6{hit} &7with a stunner!"


########################
#    Grappling Hook    #
########################

grapple_displayname: "&6Grappling Hook"

grapple_lore:
  - "&8Magical rod"
  - "&8that launches you!"

# cooldown time in seconds
grapple_cooldown_time: 60

# should the player take fall damage?
grapple_fall_damage_enabled: false


########################
#  Anti Block-up Bone  #
########################

# how many hits it takes to activate this ability
amount_of_anti_bone_hits: 3

anti_bone_displayname: "&eAnti Block-up Bone"

anti_bone_lore:
  - "&8hit a player 3 times"
  - "&8to stop them from placing"
  - "&8or mining blocks for"
  - "&e45 &8seconds."

# cooldown time in seconds
anti_bone_cooldown_time: 120

# how long the player cannot build for
anti_bone_duration: 10

# you can use {hit} to display hit player's name, and {hitter} to display hitter's name
message_to_anti_bone_hit: "&6&lAbilities &8\u00BB &6{hitter} &7hit you with an anti block-up bone, preventing you build and breaking blocks!"

message_to_anti_bone_hitter: "&6&lAbilities &8\u00BB &7You hit &6{hit} &7with an anti block-up bone!"


########################
#    Instant Apples    #
########################

crapple_displayname: "&6Instant Crapple"
gapple_displayname: "&5&lInstant God-Apple"

crapple_lore:
  - "&8Right click this item"
  - "&8to instantly eat a"
  - "&8golden apple."

gapple_lore:
  - "&8Right click this item"
  - "&8to instantly eat an"
  - "&5&lenchanted golden apple."

crapple_cooldown_time: 300
gapple_cooldown_time: 3600

message_to_crapple_eater: "&6&lAbilities &8\u00BB &7You ate an &6Instant Crapple&7!"
message_to_gapple_eater: "&6&lAbilities &8\u00BB &7You ate an &5&lInstant God-Apple&7!"


########################
#       Bamboozle      #
########################

bamboozle_displayname: "&3Bamboozle"

bamboozle_lore:
  - "&8Right click this item"
  - "&8on a player to mess"
  - "&8up their hotbar!"

bamboozle_cooldown_time: 25

# you can use {hit} to display hit player's name, and {hitter} to display hitter's name
message_to_bamboozle_hit: "&6&lAbilities &8\u00BB &6{hitter} &7hit you with &3Bamboozle&7, which messed up your hotbar!"

message_to_bamboozle_hitter: "&6&lAbilities &8\u00BB &7You hit &6{hit} &7with bamboozle!"


########################
#    Time-Warp Pearl   #
########################

time_warp_displayname: "&5&lTime-Warp Pearl"

time_warp_lore:
  - "&8Teleports you back to"
  - "&8your previous location 5"
  - "&&seconds after your pearl lands."

time_warp_cooldown_time: 25

# time before the player gets teleported to their initial location (in seconds)
time_before_warp_tp: 5

message_to_warp_pearler: "&6&lAbilities &8\u00BB &7You used a &5&lTime-Warp Pearl&7! You will be teleported back in &65 seconds!"


########################
#      Fake Pearl      #
########################

fake_pearl_displayname: "&dFake Pearl"

fake_pearl_lore:
  - "&8Get them off your"
  - "&8trail with this"
  - "&8fake pearl!"

fake_pearl_cooldown_time: 25

message_to_fake_pearler: "&6&lAbilities &8\u00BB &7You used a &dFake Pearl&7!"


########################
#        Saviour       #
########################

saviour_displayname: "&6&lSaviour"

saviour_lore:
  - "&8Your guardian angel!"
  - "&8when you die, this gives"
  - "&7you &64 &8absorption hearts"
  - "&8and &610 &8seconds of"
  - "&8regeneration &62"

regeneration_seconds: 10

saviour_cooldown_time: 300

message_to_saviour_user: "&6&lAbilities &8\u00BB &7Your &6&lSaviour&7 &7saved you from death!"


########################
#     Portable Bard    #
########################

bard_displayname: "&6&lPortable Bard"

bard_lore:
  - "&8Use this item"
  - "&8to open the &6&lPortable Bard"
  - "&8GUI."

bard_cooldown_time: 240

# must be shorter than 32 characters
bard_gui_name: "&6&lPortable Bard"

bard_strength_level: 2
bard_strength_duration: 8

bard_res_level: 3
bard_res_duration: 8


########################
#     Rabbit's Soul    #
########################

rabbit_displayname: "&2Rabbit's Soul"

rabbit_lore:
  - "&8Use this item to gain"
  - "&8speed and jump boost!"

rabbit_cooldown_time: 240

message_to_rabbit_user: "&6&lAbilities &8\u00BB &7You used a &2Rabbit's Soul&7!"

jump_boost_level: 4
jump_boost_duration: 15

speed_level: 4
speed_duration: 15


########################
#    Potion Counter    #
########################

pot_counter_displayname: "&dPotion Counter"

pot_counter_lore:
  - "&8Click a player with this"
  - "&8item to see how many"
  - "&8potions they have!"

# use {count} to show how many potions the {user} has
message_sent_to_user: "&6&lAbilities &8\u00BB &6{user} &7has &6{count} &7pots left!"

pot_counter_cooldown_time: 30


########################
#  Ghost Block (IN THE WORKS, DOESNT NOT WORK RN)     #
########################

ghost_block_displayname: ""

ghost_block_lore:
  - ""

# when player places ghost block
message_sent_to_ghost_block_placer: "&6&lAbilities &8\u00BB &6{user} &7has &6{count} &7pots left!"

# when block disappears because of restart

# message to player when they mine a ghost block

# cooldown in between usages (in seconds)
ghost_block_cooldown_time: 30