messages:
  cooldown: "&cDevi aspettare ancora &f%cooldown% secondi &cdi riutilizzare questa abilità"
  no-permission: "&cNon hai il permesso di usare questa abilità"
  use-on-target: "&cUtilizza questa abilità su un nemico"

spawn-region:
  world: "world"
  x1: 76
  y1: 130
  z1: 1221
  x2: 217
  y2: 257
  z2: 1331
  deny: "&cNon puoi utilizzare questa abilità qui"

commands:
  give:
    message: "&fHai dato &c%amount% %item% &fa &c%player%"
    usage: "&c/giveability <player> <ability> <amount>"
    offline: "&cQuesto giocatore è offline"
    invalid: "&cI parametri inseriti non sono corretti"